version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=Asia/Seoul
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'

  graylog:
    image: graylog/graylog:4.0.5
    container_name: graylog
    restart: always
    ports:
      - 9000:9000
      - 12201:12201
      - 1514:1514
      - 5555:5555
    environment:
      - GRAYLOG_ROOT_PASSWORD_SHA2=
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    depends_on:
      - mongo
      - elasticsearch